# Generated by Django 5.2.16 on 2026-07-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_approval_document_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
