# Generated by Django 5.2.16 on 2026-07-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_employee_onboarding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='zoho_user_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='workdrive_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='zoho_file_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
