# Generated by Django 5.2.16 on 2026-07-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_approvaldecision_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='requires_supporting_document',
            field=models.BooleanField(default=False, help_text='When enabled, employees must upload a supporting document (e.g. a medical note) with the request.'),
        ),
    ]
