import django.db.models.deletion
import uuid
from django.db import migrations, models

BASE = [('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('deleted_at', models.DateTimeField(blank=True, null=True))]

class Migration(migrations.Migration):
    dependencies = [('core', '0023_company_work_calendar')]
    operations = [
      migrations.AlterField(model_name='employee', name='role', field=models.CharField(choices=[('FINANCE','Finance approver'),('ADMIN','Administrator'),('SUPERVISOR','Supervisor'),('HOD','Head of Department'),('HR_ADMIN','HR Admin'),('MANAGER','Manager'),('EMPLOYEE','Employee')], default='EMPLOYEE', max_length=20)),
      migrations.CreateModel(name='PayrollConfig', fields=BASE+[('payroll_day',models.PositiveSmallIntegerField(default=25)),('leave_allowance_percent',models.DecimalField(decimal_places=2,default=0,max_digits=5)),('standard_working_days',models.PositiveSmallIntegerField(default=22)),('maximum_deduction_percent',models.DecimalField(decimal_places=2,default=100,max_digits=5)),('settlement_formats',models.JSONField(default=list)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='core.company')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee')),('updated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee'))]),
      migrations.CreateModel(name='PayrollRun', fields=BASE+[('month',models.DateField()),('status',models.CharField(default='DRAFT',max_length=20)),('total_gross',models.DecimalField(decimal_places=2,default=0,max_digits=16)),('total_deductions',models.DecimalField(decimal_places=2,default=0,max_digits=16)),('total_held',models.DecimalField(decimal_places=2,default=0,max_digits=16)),('net_payroll',models.DecimalField(decimal_places=2,default=0,max_digits=16)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='core.company')),('calculated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee')),('approved_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee')),('approved_at',models.DateTimeField(blank=True,null=True)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee')),('updated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee'))]),
      migrations.CreateModel(name='PayrollProfile', fields=BASE+[('employee_number',models.CharField(max_length=50)),('base_salary',models.DecimalField(decimal_places=2,max_digits=14)),('bank_account_ciphertext',models.TextField(blank=True)),('bank_code',models.CharField(blank=True,max_length=10)),('pension_id_ciphertext',models.TextField(blank=True)),('tax_id_ciphertext',models.TextField(blank=True)),('employment_status',models.CharField(default='ACTIVE',max_length=20)),('hire_date',models.DateField()),('termination_date',models.DateField(blank=True,null=True)),('data_processing_consented_at',models.DateTimeField(blank=True,null=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='core.company')),('employee',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='payroll_profile',to='core.employee')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee')),('updated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee'))]),
      migrations.CreateModel(name='StatutoryRule', fields=BASE+[('kind',models.CharField(max_length=30)),('rate_percent',models.DecimalField(decimal_places=4,max_digits=7)),('effective_from',models.DateField()),('effective_to',models.DateField(blank=True,null=True)),('is_active',models.BooleanField(default=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='core.company')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee')),('updated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee'))]),
      migrations.AddConstraint(model_name='payrollconfig', constraint=models.UniqueConstraint(fields=('company',),name='unique_payroll_config_company')),
      migrations.AddConstraint(model_name='payrollrun', constraint=models.UniqueConstraint(fields=('company','month'),name='unique_payroll_run_month')),
      migrations.AddConstraint(model_name='payrollprofile', constraint=models.UniqueConstraint(fields=('company','employee_number'),name='unique_payroll_employee_number')),
    ]
