# Generated by Django 5.2.16 on 2026-07-31 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_company_work_calendar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='carried_over_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='carry_over_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Maximum unused days that can be carried over to the next calendar year.', max_digits=5),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_days_per_request',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maximum days per single leave request. If null, global system default applies.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='proration_rule',
            field=models.CharField(choices=[('NONE', 'No proration'), ('LINEAR', 'Linear monthly proration')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyworkcalendar',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyworkcalendar',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'year')},
        ),
    ]
