import django.db.models.deletion
import uuid
from django.db import migrations, models
BASE=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('uuid',models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True))]
def audit(): return [('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee')),('updated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee'))]
class Migration(migrations.Migration):
 dependencies=[('core','0026_merge_leave_balance_and_payroll')]
 operations=[
  migrations.CreateModel(name='PayrollAdjustment',fields=BASE+[('kind',models.CharField(max_length=20)),('name',models.CharField(max_length=150)),('amount',models.DecimalField(decimal_places=2,max_digits=14)),('month',models.DateField()),('reason',models.TextField()),('evidence_reference',models.CharField(blank=True,max_length=500)),('status',models.CharField(default='PENDING',max_length=20)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='core.company')),('employee',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='payroll_adjustments',to='core.employee')),('approved_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee'))]+audit()),
  migrations.CreateModel(name='PayrollItem',fields=BASE+[('base_salary',models.DecimalField(decimal_places=2,max_digits=14)),('leave_allowance',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('advance',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('bonus',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('gross_pay',models.DecimalField(decimal_places=2,max_digits=14)),('total_deductions',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('held_amount',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('net_pay',models.DecimalField(decimal_places=2,max_digits=14)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='core.company')),('employee',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='payroll_items',to='core.employee')),('payroll_run',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='core.payrollrun'))]+audit()),
  migrations.CreateModel(name='PayrollDeduction',fields=BASE+[('kind',models.CharField(max_length=30)),('name',models.CharField(max_length=150)),('amount',models.DecimalField(decimal_places=2,max_digits=14)),('reason',models.TextField()),('is_held',models.BooleanField(default=False)),('contest_reason',models.TextField(blank=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='core.company')),('adjustment',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='core.payrolladjustment')),('payroll_item',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='deductions',to='core.payrollitem'))]+audit()),
  migrations.AddConstraint(model_name='payrollitem',constraint=models.UniqueConstraint(fields=('payroll_run','employee'),name='unique_payroll_item_employee')),
 ]
