import django.db.models.deletion
import uuid
from django.db import migrations, models
BASE=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('uuid',models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('deleted_at',models.DateTimeField(blank=True,null=True))]
class Migration(migrations.Migration):
 dependencies=[('core','0025_payroll_records')]
 operations=[
  migrations.AlterModelTable(name='payrollprofile',table='payroll_profiles'), migrations.AlterModelTable(name='payrollconfig',table='payroll_configs'), migrations.AlterModelTable(name='statutoryrule',table='payroll_statutory_rules'), migrations.AlterModelTable(name='payrollrun',table='payroll_runs'), migrations.AlterModelTable(name='payrolladjustment',table='payroll_adjustments'), migrations.AlterModelTable(name='payrollitem',table='payroll_items'), migrations.AlterModelTable(name='payrolldeduction',table='payroll_deductions'),
  migrations.AddField(model_name='payrolldeduction',name='contested_at',field=models.DateTimeField(blank=True,null=True)), migrations.AddField(model_name='payrolldeduction',name='resolution_notes',field=models.TextField(blank=True)),
  migrations.CreateModel(name='PayrollAuditEvent',fields=BASE+[('action',models.CharField(max_length=100)),('details',models.JSONField(default=dict)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='core.company')),('payroll_run',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='audit_events',to='core.payrollrun')),('employee',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='core.employee')),('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee')),('updated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee'))],options={'db_table':'payroll_audit_events'}),
  migrations.CreateModel(name='SettlementExport',fields=BASE+[('format',models.CharField(max_length=10)),('file_path',models.CharField(max_length=500)),('checksum',models.CharField(max_length=64)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='core.company')),('payroll_run',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='exports',to='core.payrollrun')),('exported_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='+',to='core.employee')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee')),('updated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee'))],options={'db_table':'payroll_settlement_exports'}),
  migrations.CreateModel(name='ReconciliationRecord',fields=BASE+[('bank_reference',models.CharField(max_length=100)),('result',models.CharField(max_length=20)),('details',models.JSONField(default=dict)),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='core.company')),('payroll_run',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='reconciliation',to='core.payrollrun')),('reconciled_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='+',to='core.employee')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee')),('updated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to='core.employee'))],options={'db_table':'payroll_reconciliations'}),
 ]
