# Generated by Django 5.2.17 on 2026-08-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_employee_role_loancase_loanauditevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_org_admin',
            field=models.BooleanField(default=False, help_text="Grants permission to edit the organogram: org units, and other employees' role/manager/org-unit assignments. Independent of role; grant deliberately to specific trusted people rather than to every HR Admin."),
        ),
    ]
