# Generated by Django 5.2.16 on 2026-08-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_loancase_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaldecision',
            name='stage',
            field=models.CharField(blank=True, choices=[('DEPT_HEAD', 'Department Head'), ('HR', 'HR'), ('ADMIN', 'Administrator'), ('SUPERVISOR', 'Supervisor'), ('HOD', 'Head of Department')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapprovalstep',
            name='stage',
            field=models.CharField(choices=[('DEPT_HEAD', 'Department Head'), ('HR', 'HR'), ('ADMIN', 'Administrator'), ('SUPERVISOR', 'Supervisor'), ('HOD', 'Head of Department')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING_DEPARTMENT_HEAD', 'Pending Department Head Approval'), ('PENDING_HR', 'Pending HR Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('AMENDMENT_REQUESTED', 'Amendment requested'), ('PENDING', 'Pending (legacy)')], default='PENDING_DEPARTMENT_HEAD', max_length=30),
        ),
    ]
