# Generated by Django 5.2.16 on 2026-08-13 18:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_approvaldecision_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('system_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('employee_self_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('manager_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('hr_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('calibrated_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('MANAGER_REVIEWED', 'Manager Reviewed'), ('HR_REVIEWED', 'HR Reviewed'), ('CALIBRATED', 'Calibrated'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('calibrated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrated_reviews', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_reviews',
                'unique_together': {('company', 'cycle', 'employee')},
            },
        ),
    ]
