# Generated by Django 5.2.16 on 2026-08-13 18:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_performancereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], default='NGN', max_length=3)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('meal_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reason', models.TextField(blank=True, help_text='Reason for salary change (e.g. promotion, annual review)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salary_records',
                'ordering': ['-effective_date'],
            },
        ),
    ]
