# Generated by Django 5.2.16 on 2026-08-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_salaryrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('FINANCE', 'Finance approver'), ('ADMIN', 'Administrator'), ('SUPERVISOR', 'Supervisor'), ('HOD', 'Head of Department'), ('HR_ADMIN', 'HR Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
