import { useEffect, useState } from 'react';
import { approveLeave, getPendingLeaveApprovals, PendingLeaveApproval, rejectLeave } from '../api/leaves';
import ApprovalTimeline from '../components/ApprovalTimeline';
import LoadingSpinner from '../components/LoadingSpinner';
import StatusBadge from '../components/StatusBadge';
import { useToast } from '../contexts/ToastContext';

const Reviewer = () => {
  const [rows, setRows] = useState<PendingLeaveApproval[]>([]); const [selected, setSelected] = useState<PendingLeaveApproval | null>(null); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const { addToast } = useToast();
  const load = async () => { setLoading(true); try { setRows(await getPendingLeaveApprovals()); } catch { addToast('Unable to load the approval queue.', 'error'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const decide = async (decision: 'approve' | 'reject') => { if (!selected) return; if (decision === 'reject' && !reason.trim()) { addToast('A rejection reason is required.', 'error'); return; } setBusy(true); try { decision === 'approve' ? await approveLeave(selected.uuid, reason || undefined) : await rejectLeave(selected.uuid, reason); addToast(`Leave request ${decision}d.`, 'success'); setSelected(null); setReason(''); await load(); } catch { addToast(`Unable to ${decision} this request.`, 'error'); } finally { setBusy(false); } };
  if (loading) return <LoadingSpinner />;
  return <div className="card"><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}><div><h1>Leave approval queue</h1><p style={{ color: 'var(--color-text-muted)' }}>Only requests currently assigned to you are shown.</p></div><StatusBadge status="PENDING" label={`${rows.length} awaiting action`} /></div><div className="table-container"><table><thead><tr><th>Employee</th><th>Department</th><th>Leave</th><th>Dates</th><th>Days</th><th>Stage</th><th /></tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={7}>No leave requests require your attention.</td></tr> : rows.map(row => <tr key={row.uuid}><td>{row.employee_name}<br /><small>{row.employee_id}</small></td><td>{row.org_unit || row.department || '—'}<br /><small>{row.position || '—'}</small></td><td>{row.leave_type}</td><td>{row.start_date} — {row.end_date}</td><td>{row.working_days}</td><td><StatusBadge status={row.current_approval_step.stage} /></td><td><button className="btn-primary" onClick={() => setSelected(row)}>Review</button></td></tr>)}</tbody></table></div>{selected && <div role="dialog" aria-modal="true" className="modal-overlay"><div className="card modal-content"><div style={{ display: 'flex', justifyContent: 'space-between' }}><h2>{selected.employee_name} · {selected.leave_type}</h2><button className="btn-secondary" onClick={() => setSelected(null)}>Close</button></div><p><strong>{selected.start_date} — {selected.end_date}</strong> · {selected.working_days} working days</p><p>{selected.reason}</p>{selected.supporting_document_url && <p><a href={selected.supporting_document_url} target="_blank" rel="noreferrer">View supporting document: {selected.supporting_document_name || 'Document'}</a></p>}<h3 style={{ marginTop: 16 }}>Approval timeline</h3><ApprovalTimeline steps={selected.approval_timeline} /><label style={{ display: 'block', marginTop: 16 }}>Decision note <textarea className="input-field" rows={3} value={reason} onChange={event => setReason(event.target.value)} placeholder="Required when rejecting" /></label><div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 16 }}><button className="btn-danger" disabled={busy || !selected.can_reject} onClick={() => void decide('reject')}>Reject</button><button className="btn-primary" disabled={busy || !selected.can_approve} onClick={() => void decide('approve')}>Approve</button></div></div></div>}</div>;
};
export default Reviewer;
