"""
Django settings for hr_platform project.

Generated by 'django-admin startproject' using Django 5.2.15.
"""

import os
from pathlib import Path
from urllib.parse import urlparse

from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

APP_ENV = os.environ.get('APP_ENV', 'development').strip().lower()
IS_PRODUCTION = APP_ENV in {'production', 'prod', 'live'}


def _env_flag(name: str, default: bool = False) -> bool:
    value = os.environ.get(name, str(default)).strip().lower()
    return value in {'1', 'true', 'yes', 'on'}


def _env_list(name: str, default: str = '') -> list[str]:
    raw = os.environ.get(name, default)
    if raw is None:
        return []
    return [part.strip() for part in str(raw).split(',') if part.strip()]


if IS_PRODUCTION and _env_flag('DEBUG', default=False) is True:
    raise ImproperlyConfigured('DEBUG must be False in production.')

DEBUG = _env_flag('DEBUG', default=(not IS_PRODUCTION))

# Zoho API configuration
ZOHO_CLIENT_ID = os.environ.get('ZOHO_CLIENT_ID', '')
ZOHO_CLIENT_SECRET = os.environ.get('ZOHO_CLIENT_SECRET', '')
ZOHO_REFRESH_TOKEN = os.environ.get('ZOHO_REFRESH_TOKEN', '')
ZOHO_ORG_ID = os.environ.get('ZOHO_ORG_ID', '')
ZOHO_API_BASE_URL = os.environ.get('ZOHO_API_BASE_URL', 'https://www.zohoapis.com')
ZOHO_USE_MOCK = os.environ.get('ZOHO_USE_MOCK', 'False').lower() in ('1', 'true', 'yes', 'on')
# The frontend route Zoho redirects the browser back to (OAuthCallback, mounted at
# /app/callback) after sign-in. Must be registered in the Zoho API Console exactly.
ZOHO_OAUTH_REDIRECT_URI = os.environ.get('ZOHO_OAUTH_REDIRECT_URI', 'http://localhost:5173/app/callback')
# Comma-separated allow-list for the exact frontend callback URI registered in the
# Zoho API Console. Add only deliberately registered staging/production frontend
# callback URIs in their respective environments.
ZOHO_ALLOWED_REDIRECT_URIS = os.environ.get(
    'ZOHO_ALLOWED_REDIRECT_URIS',
    ZOHO_OAUTH_REDIRECT_URI,
)
ZOHO_LOGIN_SCOPES = os.environ.get('ZOHO_LOGIN_SCOPES', 'AaaServer.profile.READ')
ZOHO_ALLOWED_EMAIL_DOMAIN = os.environ.get('ZOHO_ALLOWED_EMAIL_DOMAIN', '').lower().strip()
MAX_LEAVE_WORKING_DAYS = int(os.environ.get('MAX_LEAVE_WORKING_DAYS', '15'))
DELIVERY_JOB_LEASE_SECONDS = int(os.environ.get('DELIVERY_JOB_LEASE_SECONDS', '300'))
DELIVERY_FAILURE_ALERT_EMAIL = os.environ.get('DELIVERY_FAILURE_ALERT_EMAIL', '')

# Dedicated key for encrypting payroll/loan sensitive fields (core/security.py,
# core/loan_security.py). This key must come from the environment and must not be
# silently replaced with SECRET_KEY in production.
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY', '')

# SECRET_KEY must be configured in every deployed environment.
SECRET_KEY = os.environ.get('SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-development-only'
    else:
        raise ImproperlyConfigured('SECRET_KEY must be configured when DEBUG is disabled.')

if IS_PRODUCTION:
    insecure_defaults = {
        'django-insecure-development-only',
        'django-insecure',
        'dev-secret',
        'development-secret',
        'secret-key',
        'change-me',
        'insecure',
        'django-insecure-local-development-secret-key-change-me',
    }
    if SECRET_KEY.lower() in insecure_defaults or len(SECRET_KEY) < 50 or len(set(SECRET_KEY)) < 5:
        raise ImproperlyConfigured('SECRET_KEY is missing or unsafe for production.')
    if not FIELD_ENCRYPTION_KEY or len(FIELD_ENCRYPTION_KEY) < 32:
        raise ImproperlyConfigured('FIELD_ENCRYPTION_KEY must be configured in production.')

# Development: allow explicit localhost and Vite dev origin.
# Production: require real hosts only and no wildcards.
if IS_PRODUCTION:
    default_allowed_hosts = []
    default_csrf_origins = []
else:
    default_allowed_hosts = ['localhost', '127.0.0.1', 'testserver']
    default_csrf_origins = ['http://localhost:5173', 'http://127.0.0.1:5173']

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', ','.join(default_allowed_hosts))
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('ALLOWED_HOSTS must be configured in production.')
if IS_PRODUCTION and any(host == '*' for host in ALLOWED_HOSTS):
    raise ImproperlyConfigured('ALLOWED_HOSTS must not contain wildcard hosts in production.')

CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS', ','.join(default_csrf_origins))
if IS_PRODUCTION and not CSRF_TRUSTED_ORIGINS:
    raise ImproperlyConfigured('CSRF_TRUSTED_ORIGINS must be configured in production.')
if IS_PRODUCTION and any(origin.startswith('http://') for origin in CSRF_TRUSTED_ORIGINS):
    raise ImproperlyConfigured('Production CSRF origins must use https:// only.')
if not DEBUG and 'http://localhost:5173' not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [origin for origin in CSRF_TRUSTED_ORIGINS if origin]

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = _env_flag('SECURE_SSL_REDIRECT', default=False)
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

if IS_PRODUCTION:
    DATABASE_URL = os.environ.get('DATABASE_URL', '')
    if not DATABASE_URL:
        raise ImproperlyConfigured('DATABASE_URL must be configured in production.')
else:
    DATABASE_URL = os.environ.get('DATABASE_URL', '')


def _parse_database_url(database_url: str):
    parsed = urlparse(database_url)
    if parsed.scheme.startswith('postgres'):
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path.lstrip('/') if parsed.path else '',
            'USER': parsed.username or '',
            'PASSWORD': parsed.password or '',
            'HOST': parsed.hostname or 'localhost',
            'PORT': str(parsed.port or 5432),
        }
    return None


# Database Configuration
# Uses PostgreSQL if DATABASE_URL or POSTGRES_DB is provided, otherwise falls back to SQLite for local development/testing.
postgres_config = None
if DATABASE_URL:
    postgres_config = _parse_database_url(DATABASE_URL)
if postgres_config:
    DATABASES = {'default': postgres_config}
elif os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# from this point forward, the rest of the settings remain largely unchanged.


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',

    # Custom Apps
    'core.apps.CoreConfig',
    'zoho.apps.ZohoConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hr_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hr_platform.wsgi.application'


# Database Configuration
# Uses PostgreSQL if POSTGRES_DB is provided, otherwise falls back to SQLite for local development/testing
if os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Custom User Model
AUTH_USER_MODEL = 'core.Employee'

# See hr_platform/test_runner.py: widens Django's default test-file discovery
# pattern so *_tests.py files (security_tests.py, payroll_tests.py, etc.) are
# actually picked up by `manage.py test`, not silently skipped.
TEST_RUNNER = 'hr_platform.test_runner.ProjectTestRunner'


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'dist',
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email (Zoho SMTP)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@example.com')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.zoho.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '1000/minute'
    }
}
